name: Deploy Backend

on:
  push:
    branches:
      - master   # change to main if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e   # stop on first error

            echo "Going to project folder"
            cd /home/ubuntu/restaurant_app/zenzio_backend

            echo "Pull latest code"
            git fetch origin
            git reset --hard origin/master

            echo "Install dependencies"
            npm ci

            echo "Build project"
            npm run build

            echo "Restart app"
            pm2 restart backend || pm2 start dist/main.js --name backend

            echo "Save PM2 state"
            pm2 save

            echo "Health check"
            curl -f http://localhost:3000 || exit 1